//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use async_graphql::SimpleObject;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, SimpleObject)]
#[sea_orm(table_name = "comment")]
#[graphql(concrete(name = "Comment", params()))]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub user_id: i32,
    pub template_id: i32,
    pub parent_comment_id: Option<i32>,
    pub content: String,
    pub create_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::comment_dislikes::Entity")]
    CommentDislikes,
    #[sea_orm(has_many = "super::comment_likes::Entity")]
    CommentLikes,
    #[sea_orm(
        belongs_to = "super::template::Entity",
        from = "Column::Id",
        to = "super::template::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Template,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::Id",
        to = "super::user::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    User,
}

impl Related<super::comment_dislikes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CommentDislikes.def()
    }
}

impl Related<super::comment_likes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CommentLikes.def()
    }
}

impl Related<super::template::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Template.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
