//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub mod prelude;

pub mod category;
pub mod comment;
pub mod comment_dislikes;
pub mod comment_likes;
pub mod favorites;
pub mod tag;
pub mod template;
pub mod template_downloads;
pub mod template_history;
pub mod template_tag;
pub mod user;
