//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::category::Entity as Category;
pub use super::comment::Entity as Comment;
pub use super::comment_dislikes::Entity as CommentDislikes;
pub use super::comment_likes::Entity as CommentLikes;
pub use super::favorites::Entity as Favorites;
pub use super::tag::Entity as Tag;
pub use super::template::Entity as Template;
pub use super::template_downloads::Entity as TemplateDownloads;
pub use super::template_history::Entity as TemplateHistory;
pub use super::template_tag::Entity as TemplateTag;
pub use super::user::Entity as User;
