//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use async_graphql::SimpleObject;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, SimpleObject)]
#[sea_orm(table_name = "template_downloads")]
#[graphql(concrete(name = "TemplateDownloads", params()))]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub template_id: i32,
    pub create_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::template::Entity",
        from = "Column::Id",
        to = "super::template::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Template,
}

impl Related<super::template::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Template.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
